---
kind: pipeline
type: exec
name: build

steps:
- name: build
  environment:
    KLUCTL_VERSION: "2.27.0"
  commands:
    - make

- name: push-remote
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN_AKESTER
    KLUCTL_VERSION: "2.27.0"
  depends_on:
    - build
  commands:
    - make push-remote

  when:
      branch:
        - master